# 1. Create a 3x3x3 array with random values 

In [12]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.67227944 0.81450473 0.9048293 ]
  [0.09937322 0.35018602 0.86007859]
  [0.58550323 0.35620804 0.08287745]]

 [[0.82893563 0.27225804 0.78465049]
  [0.46689106 0.90254404 0.67547349]
  [0.02844448 0.36864138 0.11181321]]

 [[0.90057935 0.3724376  0.26081241]
  [0.09931089 0.71640118 0.87665439]
  [0.84367344 0.20359458 0.85126157]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [14]:
b = np.diag([1,2,3,4,0])
print(b)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [41]:
import numpy as np
x = np.ones((3,3),dtype=int)
print("checkboard Pattern")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

checkboard Pattern
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [30]:
import numpy as np
x=np.random.random((3,3))
print("matrix")
print(x)
print("normalize matrix")
xmax,xmin = x.max(),x.min()

x = (x - xmin)/(xmax- xmin)
print(x)

matrix
[[0.56501099 0.16493894 0.91809943]
 [0.47666473 0.29803593 0.81807501]
 [0.59939845 0.19926022 0.9363256 ]]
normalize matrix
[[0.51864009 0.         0.9763722 ]
 [0.40411095 0.17254251 0.84670386]
 [0.56321885 0.04449296 1.        ]]


# 5.  How to find common values between two arrays?

In [20]:
import numpy as np
a = np.array([1,2,3,4,5,6])
print("Array 1 =",a)
b = np.array([4,3,9,7,8])
print("Array 2 =",b)
print("common values are")
print(np.intersect1d(a,b))

Array 1 = [1 2 3 4 5 6]
Array 2 = [4 3 9 7 8]
common values are
[3 4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [26]:
import numpy as np
today = np.datetime64("today","D")
print("TODAY =",today)
yest = np.datetime64("today","D") - np.timedelta64(1,"D")
print("YEST =",yest)
tomm = np.datetime64("today","D") + np.timedelta64(1,"D")
print("TOMM =",tomm)

TODAY = 2020-07-26
YEST = 2020-07-25
TOMM = 2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [48]:
import numpy as np
a = np.random.randint(0,10,20)
print(a)
b = np.random.randint(0,10,20)
print(b)
c = np.allclose(a,b)
print(c)

[8 9 0 0 9 5 3 4 0 9 8 4 0 5 5 1 1 1 7 3]
[0 3 0 8 8 8 1 6 1 5 1 2 9 9 7 6 9 6 5 9]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [57]:
x = np.random.random(10)
print(x)
x[x.argmax()] = 0
print(x)

[0.61892836 0.13979182 0.91322923 0.13625291 0.58800951 0.02825167
 0.2909057  0.96207503 0.06066752 0.28808755]
[0.61892836 0.13979182 0.91322923 0.13625291 0.58800951 0.02825167
 0.2909057  0.         0.06066752 0.28808755]


# 9. How to print all the values of an array?

In [62]:
a = [1,2,3,4,5,6,8,9,7,10]
import numpy as np
x = np.array(a)
x

array([ 1,  2,  3,  4,  5,  6,  8,  9,  7, 10])

__10.Subtract the mean of each row of a matrix__

In [72]:
x = np.random.rand(3,4)
print(x)
x = x-x.mean(axis=1,keepdims = True)
print(x)

[[9.63545901e-01 7.87257219e-01 1.38480518e-01 3.60901969e-01]
 [8.81318936e-01 8.52233764e-01 6.97995022e-01 6.58782636e-02]
 [2.20952263e-01 7.70040341e-01 7.53151015e-04 6.92580444e-01]]
[[ 0.4009995   0.22471082 -0.42406588 -0.20164443]
 [ 0.25696244  0.22787727  0.07363853 -0.55847823]
 [-0.20012929  0.34895879 -0.4203284   0.27149889]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [82]:
x = np.array([1,2,3,4,5,6])

for i in x:
    print(x)
    x[i]=x[i]+1
    

[1 2 3 4 5 6]
[1 3 3 4 5 6]
[1 3 3 5 5 6]
[1 3 3 6 5 6]


IndexError: index 6 is out of bounds for axis 0 with size 6

# 12.How to get the diagonal of a dot product?

In [85]:
x = np.array([0,1,2,3,4,8,6,4])


TypeError: dot() missing 1 required positional argument: 'b'

# 13.How to find the most frequent value in an array?

In [90]:
x = np.array([0,1,2,3,4,8,8,8,6,4])
print(x)
print("FREQUENT VALUE")
print(np.bincount(x).argmax())

[0 1 2 3 4 8 8 8 6 4]
FREQUENT VALUE
8


# 14.How to get the n largest values of an array

In [94]:
n = np.arange(15)
print(n)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[8]


__15.How to create a record array from a regular array?__